# Setup
title:        Bowen Bao #TODO:大标题
tagline:      github pages for bao share #TODO:二级标题
url:          "https://bowenbaobao.github.io/" #TODO:TODO改为用户名
baseurl:      "/" #TODO:根目录，改为用户名
paginate:     1

# About/contact
author:
  name:       Bowen Bao  #TODO名字
  email:      baowei168@163.com  #TODO邮箱
  github:     https://github.com/bowenbaobao/ #TODO:用户名

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
